name: Linux Release

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install python
      run: |
        sudo apt-get update
        sudo apt install -y python3.9 python3-pip python3.9-venv
    - name: Install dependencies and pyinstall
      run: |
        python3.9 -m venv build
        . build/bin/activate
        python -m pip install pip==22.0.4 setuptools==60.10.0
        pip install -r requirements.txt
        pip install PyInstaller==4.10
    - name: Build binary
      run: |
        pyinstaller --onefile -n nanovna-saver nanovna-saver.py

    - name: Archive production artifacts
      uses: actions/upload-artifact@v1
      with:
        name: NanoVNASaver.linux
        path: dist/nanovna-saver
