name: Windows Release

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  release:
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [x64, ]

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
        architecture: ${{ matrix.arch }}
    - name: Install dependencies and pyinstall
      run: |
        python3 -m venv venv
        .\venv\Scripts\activate
        python3 -m pip install pip==23.3.1
        python3 -m pip install -U setuptools setuptools-scm
        python3 -m pip install -r requirements.txt
        python3 -m pip install PyInstaller==6.2.0
        python3 -m pip uninstall -y PyQt6-sip
        python3 -m pip install PyQt6-sip==13.6.0
    - name: Build binary
      run: |
        .\venv\Scripts\activate
        python3 setup.py -V
        pyinstaller --onefile --noconsole -i icon_48x48.ico -p src -n nanovna-saver.exe nanovna-saver.py
    - name: Archive production artifacts
      uses: actions/upload-artifact@v1
      with:
        name: NanoVNASaver.${{ matrix.arch }}
        path: dist/nanovna-saver.exe
