name: Linux Release

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install python
      run: |
        sudo apt-get update
        sudo apt install -y python3.9 python3-pip python3.9-venv \
          python3.9-dev \
          python3-pyqt5
    - name: Install dependencies and pyinstall
      run: |
        python3.9 -m venv build
        . build/bin/activate
        python -m pip install pip==23.0.1 setuptools==67.6.0
        pip install -r requirements.txt
        pip install PyInstaller==5.9.0
    - name: Build binary
      run: |
        . build/bin/activate
        python setup.py -V
        pyinstaller --onefile -p src -n nanovna-saver nanovna-saver.py
    - name: Archive production artifacts
      uses: actions/upload-artifact@v1
      with:
        name: NanoVNASaver.linux
        path: dist/nanovna-saver
